name: Proposition de fonctionnalité
description: Proposer une amélioration ou une nouvelle fonctionnalité
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Quel problème cela résout-il ?
      description: Quel besoin ou quelle limitation actuelle motive cette demande ?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Solution proposée
      description: À quoi ressemblerait l'API ou le comportement souhaité ?
      render: python
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
    validations:
      required: false
